eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  zipkin:
    base-url: http://localhost:9211
  application:
    name: service-rpc1
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bilibili?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
feign:
  hystrix:
    enabled: true
    config:
      stream:
        maxConcurrentConnections: 50
    command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#    command:
#      default:
#        execution:
#          isolation:
#            strategy: SEMAPHORE
management:
  security:
    enabled: false
logging:
  file: D:\logback\${spring.application.name}-${server.port}.log