eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7088
spring:
  application:
    name: service-admin
  boot:
    admin:
      turbine:
        enabled: true
        clusters: SERVICE-ZUUL,SERVICE-RPC2
        location: service-turbine
management:
  security:
    enabled: false
info:
  version: ${project.version}
logging:
  file: D:\logback\${spring.application.name}-${server.port}.log